### ISSUE TITLE
audyt kod oskara

### ISSUE THREAD

**Issue by Janek1010** [Apes2getherStrong/Backend-WayToGo#45]
odpowiedzialny obywatel 'małp silnych razem' złożył obywatelski donos, że kod użytkownika Drillll jest wysoce nieprofesjonalny, zawiera duzo błędów, zle uzywa np. patcha i puta, nie zwraca dobrych kodow, nie przejmuje wyjatkow a także testy nie pokrywają praktycznie tego co powinny. W związku z powyższym zostaje zlecony audyt użytkownikowi Kondziow(to wcale nie jest anonimowy donosiciel).

**Comment by Janek1010** [comment]
![Michael-Jackson-Popcorn-GIF-Meme-Eating-Popcorn-Featured-StudioBinder](https://github.com/Apes2getherStrong/Backend-WayToGo/assets/62665388/88526634-4e21-42b8-86de-f50e22bb0a5e)

**Comment by Kondziow** [comment]
aaaa

**Comment by Kondziow** [comment]
![image](https://github.com/Apes2getherStrong/Backend-WayToGo/assets/101991466/5b22853e-6256-4094-a671-079975d40a55)

**Comment by Kondziow** [comment]
![image](https://github.com/Apes2getherStrong/Backend-WayToGo/assets/101991466/7da8cdb3-1fd8-4873-8cc6-59a9f6c09c6e)

**Comment by Kondziow** [comment]
Brak testu na patch na bledne id

**Comment by Kondziow** [comment]
![image](https://github.com/Apes2getherStrong/Backend-WayToGo/assets/101991466/76fa11f7-0ac6-4a27-b1c2-d5f15a0f8db4)
Put mial updatowac istniejacy element, a nie tworzyc nowy
